### ISSUE TITLE
[Question] Labelled Images

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/hcaptcha-challenger#153]
## Brief description

I just have 3 questions:
1. How many labelled images do you have to train your ai?
2. Are these labelled pictures publicly available?
3. Are you still training/planning to train AIs? (Last commit was over a week ago)

**Comment by Vinyzu** [comment]
Edit: I found [this](https://github.com/QIN2DIM/img_pool) But it doesnt seem like you update it much and i doubt you trained your ai on 200 images right?

**Comment by QIN2DIM** [comment]
You can follow [beiyuouo/hcaptcha-model-factory 🏗](https://github.com/beiyuouo/hcaptcha-model-factory) for more details.

>How many labelled images do you have to train your ai?

Sometimes, in order to quickly distribute the solution (within 1H), 200 pictures are sufficient, but usually a total of 500 positive and negative cases are required. We usually use data enhancement to get more imgs.

> Are these labelled pictures publicly available?

using materials at hand.

> Are you still training/planning to train AIs?

We run an early warning bot and a smaller challenger that are guaranteed to collect a sufficient amount of datasets as soon as a new challenge is discovered. We need to classify these datasets (typically 62 images/minute).

Usually we only need to update the new challenge issue and process the dataset when we have time, the rest of the model training and export is fully automated.

In addition, I found that this project does not have a good tutorial on how to contribute, so it may not be easy for others to contribute their own models.

**Comment by QIN2DIM** [comment]
> Edit: I found [this](https://github.com/QIN2DIM/img_pool) But it doesnt seem like you update it much and i doubt you trained your ai on 200 images right?

This content is only used for external links for blogging purposes.
