### ISSUE TITLE
[Challenge] Bedroom

### ISSUE THREAD

**Issue by kakapela** [QIN2DIM/hcaptcha-challenger#69]
### Prompt[en]

Please click each image containing a bedroom

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=50d5f7a9-8aed-4244-aea5-20a291951e93

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=50d5f7a9-8aed-4244-aea5-20a291951e93

### Screenshot of the challenge

![example_1](https://user-images.githubusercontent.com/34391192/178562152-30a69c15-6430-42aa-b734-e6034c66427a.JPG)
![example_2](https://user-images.githubusercontent.com/34391192/178562174-541fdfdb-8c9f-4b04-b2f9-44b6bd8c157b.JPG)
![example_3](https://user-images.githubusercontent.com/34391192/178562181-4e95896a-25c7-4249-ac3a-ff7089df2106.JPG)

**Comment by QIN2DIM** [comment]
Death is coming

**Comment by QIN2DIM** [comment]
puzzling...I don't know if the hCaptcha developers have done these questions. I can't tell if some of the images are bedroom or not, but I'm sure the AI is way ahead of me.😂😂

**Comment by QIN2DIM** [comment]
Maybe it's related to my experience, I observed the data set and I feel that the engineers have defaulted to the bedroom and living room being separate when generating the data. However, some countries may have only one room for a household because of certain issues.

See the sofa will subconsciously think that this is the living room, see the bed will subconsciously think that this is the bedroom. Stereotypes can lead to ambiguity. 😶‍🌫️
