### ISSUE TITLE
[*Challenge] image label area select

### ISSUE THREAD

**Issue by beiyuouo** [QIN2DIM/hcaptcha-challenger#82]
### Prompt[en]

Draw a tight bounding box around the concept stated in the text below. If there is more than one,choose freely.

### New types of challenge

New approach (for ex. image watermark)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

<img width="45%" alt="Snipaste_2022-07-15_02-40-10" src="https://user-images.githubusercontent.com/44976445/179196481-5faa8b95-0fe6-4fe8-8fb1-819b10e08850.png">

**Comment by QIN2DIM** [comment]
https://user-images.githubusercontent.com/62018067/179223582-6a3d7207-d6b8-40f9-8b36-15a30ab3e904.mp4

**Comment by QIN2DIM** [comment]
I solved it gracefully. Interesting experience. 

If you know which website this `sitekey` belongs to, you can leave a comment here/👻

**Comment by M-Zubair10** [comment]
This can be done using computer vsion cv2 easily right? by removing background -> finding contours and getBoundingRect()

**Comment by QIN2DIM** [comment]
😂？？

**Comment by QIN2DIM** [comment]
So how do you know which object you need to get?

**Comment by M-Zubair10** [comment]
There is always one object,
You said you solved it, how? which model? can I get the code?

**Comment by QIN2DIM** [comment]
This still doesn't stop the bots from moving, because all the challenges for developers so far are still "mental work" rather than "physical work".
![5ffced85ee4866f4894cc4c01563ff1b](https://user-images.githubusercontent.com/62018067/184475552-fb017aa3-c394-4a6e-a115-feb0470ef033.jpg)
![c15cd3b9c3bbaa38a75691016b0c151e](https://user-images.githubusercontent.com/62018067/184475557-30a6cccd-40d5-4814-a696-3a09ca0dc354.jpg)
![de1715281d201651525c88911c66bfb8](https://user-images.githubusercontent.com/62018067/184475558-c58af767-229b-4428-be4d-cc135e3517f8.jpg)
![e5abe78158cae47d15efd11ec789c8d4](https://user-images.githubusercontent.com/62018067/184475561-3c74ce2e-f35e-4a53-a414-6e22f000742a.jpg)
![fd4278b8370d7156ce0986cf86f572ff](https://user-images.githubusercontent.com/62018067/184475562-5fa02052-e979-40dd-911f-e476eef136a4.jpg)

**Comment by M-Zubair10** [comment]
Did you solved it?
I need it

**Comment by 2xmonth** [comment]
> Did you solved it?
> 
> I need it



Steps:
Predict objects in the image
Extract coordinate info (I'm pretty sure the bbox coords are in some pandas output if your use torch hub to predict)
Then just click and drag from one coordinate to the next

**Comment by QIN2DIM** [comment]
It's not that simple 😂

**Comment by Pocker88** [comment]
Hello Admin, Sir can you add this pack pictures..?!?
![216040976-41b4aeb5-f529-476e-87de-ae6faacf14d5](https://user-images.githubusercontent.com/79075067/216087710-a132ff3c-fef6-430a-a5c8-1b5e5f843ce3.jpg)

**Comment by QIN2DIM** [comment]
@Pocker88 sure, But I don't have enough data sets right now. Can you provide a stable sitekey for the forest?

**Comment by Pocker88** [comment]
Sir can you help, how can I make it?!?
